import crypto from 'node:crypto';

export const trainingMasterCopy = {
  name: 'My Coach',
  version: 'Training Master Copy v1',
  source: 'MyCoachNow_MasterCopy.docx',
  domain: 'Maruti Suzuki Arena & Nexa coaching',
  speedFramework: [
    { id: 'start_right', label: 'Start Right', weight: 15, purpose: 'Build rapport, credibility, and trust quickly.', behaviors: ['Greet warmly', 'Offer seat/refreshment', 'Use an icebreaker', 'State clear intent', 'Confirm first or return visit'], redFlags: ['Jumping to price', 'Generic scripted opener', 'No introduction'], keywords: ['welcome', 'good morning', 'welcome back', 'pleasure to meet', 'please have a seat', 'first visit', 'return visit'] },
    { id: 'plan_to_probe', label: 'Plan to Probe', weight: 25, purpose: 'Discover needs, lifestyle, usage, family, geography, finance, and aspirations.', behaviors: ['Ask open-ended questions', 'Listen actively', 'Take notes', 'Mirror and paraphrase', 'Probe deeper'], redFlags: ['Closed questions only', 'Interrupting', 'No follow-up probing'], keywords: ['what', 'how many', 'how often', 'tell me about', 'budget', 'family', 'drive', 'need', 'want', 'prefer'] },
    { id: 'explain_value_proposition', label: 'Explain Value Proposition', weight: 25, purpose: 'Map features to needs using FAB.', behaviors: ['Recommend based on probing', 'Use FAB', 'Reference customer words', 'Show the car', 'Present max two options'], redFlags: ['Reading spec sheet', 'Too many options'], keywords: ['because', 'which means', 'for you', 'based on', 'recommend', 'best fit', 'feature', 'benefit', 'advantage'] },
    { id: 'eliminate_objection', label: 'Eliminate Objection', weight: 25, purpose: 'Handle concerns with empathy and evidence.', behaviors: ['Never interrupt', 'Never argue', 'Use Acknowledge-Clarify-Evidence', 'Confirm resolution'], redFlags: ['Defensive tone', 'Immediate discounting'], keywords: ['too expensive', 'cheaper', 'not sure', 'think about it', 'concern', 'build quality', 'looks', 'online'] },
    { id: 'drive_closure', label: 'Drive Closure', weight: 10, purpose: 'Move to a decision or next step.', behaviors: ['Ask for the decision', 'Confirm next step', 'Capture follow-up'], redFlags: ['No close', 'No next step'], keywords: ['shall we', 'book', 'test drive', 'follow up', 'next step', 'decision', 'reserve', 'close'] },
  ],
  fundamentalQuestions: [
    { id: 'Q1', section: 'visit_context', question: 'First visit, return visit, or referral?', why: 'Sets context', keywords: ['first visit', 'return visit', 'welcome back', 'referral'] },
    { id: 'Q2', section: 'visit_context', question: 'What is the customer name?', why: 'Rapport', keywords: ['your name', 'called', 'mr ', 'ms ', 'mrs '] },
    { id: 'Q3', section: 'visit_context', question: 'How did they hear about us?', why: 'Personalization', keywords: ['heard about', 'came from', 'referred by', 'saw online'] },
    { id: 'Q4', section: 'visit_context', question: 'Did they research before coming in?', why: 'Buying journey', keywords: ['researched', 'looked at', 'youtube', 'online', 'website'] },
    { id: 'Q5', section: 'visit_context', question: 'Are they the sole decision maker?', why: 'Joint visit strategy', keywords: ['spouse', 'wife', 'husband', 'parent', 'decision maker'] },
    { id: 'Q6', section: 'usage', question: 'Primary use: city, highway, mixed?', why: 'Body type and engine fit', keywords: ['city', 'highway', 'mixed', 'commute'] },
    { id: 'Q7', section: 'usage', question: 'Approx km per month or year?', why: 'Fuel cost', keywords: ['km', 'per month', 'per year', 'daily drive'] },
    { id: 'Q8', section: 'usage', question: 'Solo driving or with passengers?', why: 'Seating and comfort', keywords: ['solo', 'passengers', 'with family'] },
    { id: 'Q9', section: 'usage', question: 'Driver or hired driver?', why: 'Gearbox and comfort', keywords: ['driver', 'chauffeur', 'hired', 'self drive'] },
    { id: 'Q10', section: 'geography', question: 'Any hills, bad roads, flooding?', why: 'Ground clearance and AWD', keywords: ['hills', 'bad roads', 'flood', 'waterlogging', 'rough road'] },
    { id: 'Q11', section: 'geography', question: 'Parking: open, covered, or tight?', why: 'Compact vs full-size', keywords: ['parking', 'tight space', 'garage', 'covered'] },
    { id: 'Q12', section: 'family', question: 'How many will travel regularly?', why: 'Seating requirement', keywords: ['family of', 'members', 'seat'] },
    { id: 'Q13', section: 'family', question: 'Children or elderly in the family?', why: 'Safety and entry/exit', keywords: ['children', 'kids', 'elderly', 'parents'] },
    { id: 'Q14', section: 'family', question: 'School runs or outstation trips?', why: 'Practical usage', keywords: ['school', 'outstation', 'hospital', 'trip'] },
    { id: 'Q15', section: 'family', question: 'Carry luggage, stroller, or equipment?', why: 'Boot space', keywords: ['luggage', 'boot', 'stroller', 'bag'] },
    { id: 'Q16', section: 'lifestyle', question: 'Is there a pet?', why: 'Accessory needs', keywords: ['pet', 'dog', 'cat'] },
    { id: 'Q17', section: 'lifestyle', question: 'Outdoor/adventure or urban/professional?', why: 'Profile positioning', keywords: ['adventure', 'rugged', 'urban', 'professional', 'office'] },
    { id: 'Q18', section: 'finance', question: 'What is the budget range?', why: 'Immediate filter', keywords: ['budget', 'lakh', 'on-road', 'ex-showroom'] },
    { id: 'Q19', section: 'finance', question: 'Cash purchase or EMI/finance?', why: 'Finance manager', keywords: ['emi', 'finance', 'cash', 'loan'] },
    { id: 'Q20', section: 'finance', question: 'Comfortable monthly EMI?', why: 'Variant choice', keywords: ['per month', 'monthly payment', 'emi'] },
    { id: 'Q21', section: 'finance', question: 'Existing car for trade-in?', why: 'True Value', keywords: ['exchange', 'trade-in', 'old car'] },
    { id: 'Q22', section: 'finance', question: 'How soon do they want delivery?', why: 'Urgency', keywords: ['soon', 'immediately', 'delivery', 'timeline'] },
    { id: 'Q23', section: 'finance', question: 'Corporate/government discount eligibility?', why: 'Value and urgency', keywords: ['corporate', 'government', 'discount'] },
    { id: 'Q24', section: 'preferences', question: 'Fuel preference: petrol, CNG, hybrid, electric?', why: 'Model elimination', keywords: ['petrol', 'cng', 'hybrid', 'electric', 'ev'] },
    { id: 'Q25', section: 'preferences', question: 'Transmission preference?', why: 'Comfort and convenience', keywords: ['manual', 'automatic', 'amt', 'cvt'] },
    { id: 'Q26', section: 'preferences', question: 'Color preference or avoidance?', why: 'Stock check', keywords: ['color', 'colour', 'shade', 'avoid'] },
    { id: 'Q27', section: 'preferences', question: 'Feature wishlist?', why: 'Variant choice', keywords: ['sunroof', 'wireless charging', 'adas', 'camera', 'feature'] },
    { id: 'Q28', section: 'preferences', question: 'What car do they currently drive?', why: 'Expectation baseline', keywords: ['currently drive', 'existing car', 'old car'] },
    { id: 'Q29', section: 'preferences', question: 'What is missing in their current car?', why: 'Buying motivation', keywords: ['missing', 'wish', 'need more', 'problem with current'] },
    { id: 'Q30', section: 'preferences', question: 'Competitor car they looked at and why not?', why: 'Competitive positioning', keywords: ['competitor', 'compared', 'looked at', 'why not'] },
  ],
  customerProfiles: [
    { id: 'first_time_buyer', label: 'First-Time Buyer', signals: ['young', 'single', 'city', 'budget under 8', 'parking'], idealRecommendation: ['Swift', 'Baleno', 'Celerio', 'S-Presso'], avoid: ['Ertiga', 'Grand Vitara', 'Invicto'] },
    { id: 'nuclear_family', label: 'Nuclear Family', signals: ['school run', 'boot space', 'safety', 'family of 4', 'family of 5'], idealRecommendation: ['Brezza', 'Fronx', 'Grand Vitara', 'Dzire'], avoid: ['S-Presso', 'Celerio', 'Alto K10'] },
    { id: 'large_family', label: 'Large Family', signals: ['7 seater', 'elderly', 'outstation', 'large family'], idealRecommendation: ['Ertiga', 'XL6', 'Invicto', 'Victoris'], avoid: ['hatchback', 'compact sedan'] },
    { id: 'mileage_first', label: 'Mileage-First Buyer', signals: ['high km', 'running cost', 'cng', 'hybrid', 'fleet', 'taxi'], idealRecommendation: ['Alto K10 CNG', 'Wagon R CNG', 'Dzire CNG', 'Grand Vitara Hybrid'], avoid: ['premium variants without cng'] },
    { id: 'highway_warrior', label: 'Highway Warrior', signals: ['highway', 'outstation', 'cruise control', 'comfort', 'big fuel tank'], idealRecommendation: ['Grand Vitara', 'Baleno', 'Ciaz', 'Victoris'], avoid: ['city-only hatchbacks'] },
    { id: 'adventure_seeker', label: 'Adventure Seeker', signals: ['rugged', 'masculine', 'off-road', 'ground clearance', 'awd'], idealRecommendation: ['Jimny', 'Brezza', 'Victoris AWD'], avoid: ['Baleno', 'Ignis', 'Swift'] },
    { id: 'premium_upgrader', label: 'Premium Upgrader', signals: ['upgrade', 'more features', 'prestige', 'wagonr', 'dzire'], idealRecommendation: ['Fronx', 'Baleno', 'Ciaz', 'XL6', 'Grand Vitara'], avoid: ['entry models they already own'] },
    { id: 'ev_curious', label: 'EV Curious Buyer', signals: ['electric', 'range', 'home charging'], idealRecommendation: ['e-Vitara'], avoid: ['push cng/petrol without addressing ev'] },
    { id: 'budget_maximiser', label: 'Budget Maximiser', signals: ['best features for money', 'comparison shopper', '5-8'], idealRecommendation: ['Swift ZXi+', 'Baleno Alpha', 'Fronx Delta+'], avoid: ['bare base variants'] },
    { id: 'corporate_buyer', label: 'Corporate Buyer', signals: ['multiple units', 'corporate', 'fleet', 'uniform colour'], idealRecommendation: ['Dzire CNG', 'Wagon R CNG', 'Swift bulk'], avoid: ['premium single units'] },
  ],
  objectionLibrary: [
    { id: 'price_too_expensive', label: 'It is too expensive', keywords: ['too expensive', 'pricey', 'high price', 'costly', 'on-road too high'], strategy: 'Reframe Cost' },
    { id: 'competitor_cheaper', label: 'Competitor is cheaper', keywords: ['cheaper', 'lower price', 'competitor', 'same thing cheaper'], strategy: 'TCO Comparison' },
    { id: 'wait_for_discount', label: 'I will wait for a discount', keywords: ['wait for', 'sale', 'discount', 'later'], strategy: 'Genuine Urgency' },
    { id: 'looks_objection', label: 'I do not like the looks', keywords: ['looks', 'design', 'style', 'ugly'], strategy: 'Alternative + Test' },
    { id: 'build_quality', label: 'Build quality feels light', keywords: ['build quality', 'light', 'cheap', 'weak'], strategy: 'Proof & Demo' },
    { id: 'bigger_car', label: 'I want a bigger car', keywords: ['bigger car', 'more space', 'larger', 'bigger'], strategy: 'Needs Clarification' },
    { id: 'think_about_it', label: 'Let me think about it', keywords: ['think about it', 'need time', 'decide later'], strategy: 'Identify Open Loop' },
    { id: 'spouse_needed', label: 'My spouse or family needs to see it', keywords: ['spouse', 'family needs', 'need to see'], strategy: 'Joint Visit Close' },
    { id: 'online_research', label: 'I saw a better option online', keywords: ['youtube', 'online', 'saw a better option', 'reviewed'], strategy: 'Engage Research' },
  ],
  productCatalog: [
    { model: 'Alto K10', segment: 'A-Segment Hatchback', fuel: ['petrol', 'cng'], seating: 5, priceBand: 'Under 5 lakh', tags: ['city', 'budget', 'first-time buyer'], recommendationHints: ['city commute', 'budget', 'parking'], keyFeatures: ['compact', 'CNG', 'easy to park'] },
    { model: 'S-Presso', segment: 'A+ Mini-SUV Hatchback', fuel: ['petrol', 'cng'], seating: 5, priceBand: '5-7 lakh', tags: ['budget', 'urban'], recommendationHints: ['parking', 'budget', 'solo'], keyFeatures: ['high seating position', 'CNG', 'compact footprint'] },
    { model: 'Celerio', segment: 'A-Segment Hatchback', fuel: ['petrol', 'cng'], seating: 5, priceBand: '5-7 lakh', tags: ['mileage', 'city'], recommendationHints: ['mileage', 'city', 'budget'], keyFeatures: ['efficient', 'compact', 'easy drive'] },
    { model: 'Wagon R', segment: 'Tall Hatchback', fuel: ['petrol', 'cng'], seating: 5, priceBand: '5-7 lakh', tags: ['family', 'fleet'], recommendationHints: ['mileage', 'city', 'practical'], keyFeatures: ['tall cabin', 'CNG', 'practical boot'] },
    { model: 'Eeco', segment: 'Van / MUV', fuel: ['petrol', 'cng'], seating: 5, priceBand: '5-7 lakh', tags: ['cargo', 'fleet'], recommendationHints: ['cargo', 'fleet', 'business'], keyFeatures: ['large space', 'sliding doors', 'low running cost'] },
    { model: 'Swift', segment: 'Premium Hatchback', fuel: ['petrol', 'cng'], seating: 5, priceBand: '5-9 lakh', tags: ['young', 'upgrade', 'city'], recommendationHints: ['first-time buyer', 'budget maximiser', 'city'], keyFeatures: ['sporty', 'connected features', 'efficient'] },
    { model: 'Dzire', segment: 'Compact Sedan', fuel: ['petrol', 'cng'], seating: 5, priceBand: '6-10 lakh', tags: ['family', 'fleet', 'safety'], recommendationHints: ['family', 'mileage', 'sedan'], keyFeatures: ['boot space', '5-star safety', 'CNG'] },
    { model: 'Brezza', segment: 'Compact SUV', fuel: ['petrol', 'cng'], seating: 5, priceBand: '8-14 lakh', tags: ['family', 'suv', 'city-highway'], recommendationHints: ['family', 'mixed use', 'compact suv'], keyFeatures: ['sunroof', '360 camera', 'high ground clearance'] },
    { model: 'Ertiga', segment: '7-Seater MPV', fuel: ['petrol', 'cng'], seating: 7, priceBand: '9-13 lakh', tags: ['large family', 'practical'], recommendationHints: ['family', '7 seater', 'outstation'], keyFeatures: ['7 seats', 'captain seats', 'CNG'] },
    { model: 'Victoris', segment: 'Mid-Size SUV', fuel: ['petrol', 'cng', 'hybrid'], seating: 5, priceBand: '10-20 lakh', tags: ['premium', 'tech', 'awd'], recommendationHints: ['highway', 'safety', 'awd'], keyFeatures: ['ADAS', 'AWD', 'strong hybrid'] },
    { model: 'Ignis', segment: 'Crossover Hatchback', fuel: ['petrol'], seating: 5, priceBand: '5-7 lakh', tags: ['urban', 'style'], recommendationHints: ['urban', 'style', 'young'], keyFeatures: ['quirky design', 'city friendly'] },
    { model: 'Baleno', segment: 'Premium Hatchback', fuel: ['petrol'], seating: 5, priceBand: '6-10 lakh', tags: ['upgrade', 'tech'], recommendationHints: ['upgrade', 'premium hatchback', 'tech'], keyFeatures: ['rear space', 'infotainment', 'connected features'] },
    { model: 'Fronx', segment: 'Crossover SUV', fuel: ['petrol'], seating: 5, priceBand: '7-12 lakh', tags: ['style', 'upgrade'], recommendationHints: ['style', 'premium upgrade', 'city-highway'], keyFeatures: ['crossover stance', 'turbo option', 'sunroof'] },
    { model: 'XL6', segment: '6-Seater MPV', fuel: ['petrol', 'cng'], seating: 6, priceBand: '11-14 lakh', tags: ['premium family', 'captain seats'], recommendationHints: ['family', '6 seater', 'premium'], keyFeatures: ['captain seats', 'premium interior', 'CNG'] },
    { model: 'Grand Vitara', segment: 'Mid-Size SUV', fuel: ['petrol', 'hybrid'], seating: 5, priceBand: '10-20 lakh', tags: ['highway', 'premium', 'efficiency'], recommendationHints: ['highway', 'hybrid', 'fuel efficiency'], keyFeatures: ['strong hybrid', 'ADAS', 'AWD'] },
    { model: 'Invicto', segment: 'Premium MPV', fuel: ['hybrid'], seating: 7, priceBand: '25-29 lakh', tags: ['premium family', 'executive'], recommendationHints: ['large family', 'premium', 'hybrid'], keyFeatures: ['premium hybrid', '7/8 seats', 'highway comfort'] },
    { model: 'Jimny', segment: 'Off-road SUV', fuel: ['petrol'], seating: 4, priceBand: '12-15 lakh', tags: ['adventure', 'rugged'], recommendationHints: ['adventure', 'off-road', 'rugged'], keyFeatures: ['4x4', 'rugged', 'compact'] },
    { model: 'e-Vitara', segment: 'EV SUV', fuel: ['electric'], seating: 5, priceBand: '11-20 lakh', tags: ['ev', 'tech'], recommendationHints: ['ev curious', 'charging', 'range'], keyFeatures: ['fast charging', 'ADAS', '5-star safety'] },
    { model: 'Ciaz', segment: 'Sedan', fuel: ['petrol'], seating: 5, priceBand: '10-15 lakh', tags: ['highway', 'comfort'], recommendationHints: ['highway', 'comfort', 'chauffeur'], keyFeatures: ['long-wheelbase comfort', 'boot space', 'highway cruiser'] },
  ],
  productDecisionTree: [
    { condition: 'budget under 5', recommendations: ['Alto K10', 'S-Presso'] },
    { condition: 'budget 5 to 7', recommendations: ['Alto K10', 'S-Presso', 'Celerio', 'Wagon R', 'Ignis', 'Swift'] },
    { condition: 'budget 7 to 10', recommendations: ['Swift', 'Baleno', 'Fronx', 'Dzire', 'Brezza', 'Wagon R'] },
    { condition: 'budget 10 to 15', recommendations: ['Brezza', 'Grand Vitara', 'Victoris', 'XL6', 'Fronx', 'e-Vitara'] },
    { condition: 'budget above 20', recommendations: ['Invicto', 'e-Vitara'] },
    { condition: 'seating 2 to 4', recommendations: ['Alto K10', 'S-Presso', 'Swift', 'Baleno', 'Dzire', 'Ignis', 'Fronx'] },
    { condition: 'seating 4 to 5', recommendations: ['Brezza', 'Grand Vitara', 'Victoris', 'Dzire'] },
    { condition: 'seating 6', recommendations: ['XL6'] },
    { condition: 'seating 7', recommendations: ['Ertiga', 'Invicto'] },
    { condition: 'use case city only', recommendations: ['Alto K10', 'Celerio', 'S-Presso', 'Wagon R', 'Swift', 'Baleno'] },
    { condition: 'use case highway', recommendations: ['Grand Vitara', 'Baleno', 'Dzire', 'Victoris', 'Invicto'] },
    { condition: 'use case off-road', recommendations: ['Jimny', 'Victoris AWD', 'Grand Vitara AWD'] },
    { condition: 'use case ultra low running cost', recommendations: ['Alto K10 CNG', 'Wagon R CNG', 'Dzire CNG', 'Grand Vitara Hybrid'] },
    { condition: 'use case tech', recommendations: ['e-Vitara', 'Grand Vitara Hybrid', 'Victoris Hybrid'] },
  ],
  researchTaskLibrary: [
    'Study the strong hybrid vs mild hybrid difference in Grand Vitara and Victoris.',
    'Memorise the NCAP ratings for all Maruti models in the master copy.',
    'Learn the CNG and hybrid running-cost story for your key customer segments.',
    'Study the 5-year total cost of ownership logic for petrol vs CNG vs hybrid.',
    'Review the e-Vitara story: range, charging, and feature explanation.',
    'Practice the FAB method on the top three models for your showroom segment.',
    'Review Invicto and how to position it against premium MPVs.',
    'Practice asking what is missing in the customer’s current car.',
    'Practice the return-visit opener and joint-visit reset.',
  ],
  reportTemplate: {
    summarySections: ['overall_score', 'speed_breakdown', 'question_coverage', 'product_fit', 'objections', 'strengths', 'improvements', 'next_visit', 'research_tasks'],
    gradeBands: [
      { min: 90, grade: 'A+', meaning: 'Exceptional' },
      { min: 80, grade: 'A', meaning: 'Strong' },
      { min: 65, grade: 'B', meaning: 'Good foundation' },
      { min: 50, grade: 'C', meaning: 'Below expectations' },
      { min: 0, grade: 'D', meaning: 'Needs urgent intervention' },
    ],
  },
};

export function masterCopySnapshot() {
  return {
    id: crypto.randomUUID(),
    version: trainingMasterCopy.version,
    source: trainingMasterCopy.source,
    content: trainingMasterCopy,
    createdAt: new Date().toISOString(),
  };
}
